icons = "awesome5"

[theme]
name = "space-villain"
[theme.overrides]
good_bg = "#06060f"

# [[block]]
# block = "focused_window"
# max_width = 50
# show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp59s0"
signal_strength = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

# [[block]]
# block = "cpu"
# interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%m-%d %R"
