#!/usr/bin/perl

use v5.42;
use utf8;

my @urls;
for (split /\n/, $ENV{fx}) {
    s/([^-\/:_.!'()~A-Za-z0-9])/sprintf '%%%02X', ord($1)/ge;  # percent-encode
    push @urls, "file://$_";
}

my $word = @urls == 1 ? "path" : "paths";
my $paths = $ENV{fx} =~ s/\n/ /gr;
say "Copied $word to clipboard: $paths";

exec qw(wl-copy -t text/uri-list), (join "\n", @urls);
