#!/usr/bin/perl

use v5.42;
use utf8;

my $home = $ENV{HOME};
my $pwd = $ENV{PWD};

if ($#ARGV == 0 && $ARGV[0] eq '--zoxide') {
    system ('zoxide', 'add', '--', $pwd) == 0 or die;
}

# Set terminal emulator window title.
my $pwd_title = $pwd =~ s/^\Q$home/~/r;
my $osc_title = "\e]0;${pwd_title} – lf\a";

# Inform terminal emulator of current directory, so it is propagated
# to new windows the user may create.
my $pwd_pctenc = $pwd =~ s/([^-\/:_.!'()~A-Za-z0-9])/sprintf '%%%02X', ord($1)/ger;
my $osc_cwd = "\e]7;file://${pwd_pctenc}\e\\";

my $tty_arg = ($osc_title . $osc_cwd) =~ s/(["\\])/\\$1/gr;
exec 'lf', '-remote', qq(send $ENV{id} tty-write "$tty_arg");
