#!/usr/bin/perl

use v5.42;
use utf8;

open(my $fh, '-|', qw(zoxide query --exclude), $ENV{PWD}, @ARGV) or die;
my $result;
{ local $/ = undef; $result = <$fh>; }
chomp $result;
close $fh;
die unless $? == 0;
$result =~ s/(["\\])/\\$1/g;
exec 'lf', '-remote', qq(send $ENV{id} cd "$result");
